sudo: required

language: python

services:
  - docker

install:
- docker pull tp33/django
- docker pull mysql:5.7.14
- docker pull haproxy:1.7
- mkdir db
- docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
- sleep 20
- docker build -t my-haproxy .

before_script:
- docker-compose up -d
- sleep 20
script:
- docker exec -it models_container bash -c "cd models && python manage.py test"

after_script:
- docker-compose stop
- docker stop mysql